### ISSUE TITLE
Can I have a sample .csv file?

### ISSUE THREAD

**Issue by teerathut** [webb34/Call-log-reports#1]
Hi Chris,

I downloaded the .au3 file and tried to execute. But unable to reproduce any HTML report. Perhaps the raw data of the call log I used was in a wrong format. And I'm not sure what's the right format should be. From the code, I think it requires a few column name like Department?

Could you share with us a sample of .csv file you used? Maybe remove all confidential data, just a blank template is okay. Thank you so much in advance.

**Comment by webb34** [comment]
Hi there! I just uploaded a .csv to be used with the script. It should make things quite a bit clearer.

**Comment by teerathut** [comment]
Thank you so much Chris, just downloaded it today and work like a charm. Will try to load my data in later and see how to go from here. Have a great day :)
